# -*- coding: utf-8 -*-
"""TextSplitter_LangChain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17mlGNlk0n_X-xioDx5B8wKq1uNcTytU-
"""

!pip install -q langchain pypdf

!pip install langchain langchain-community

from langchain_community.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

from google.colab import files
uploaded = files.upload()

from langchain_community.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter

# File load
loader = TextLoader("company_policy.txt")
documents = loader.load()

# Split into chunks
text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
docs = text_splitter.split_documents(documents)

print(f"Total chunks created: {len(docs)}")